### PR TITLE
Making href_key unique to the destination email to keep from caching URLs...

### PR DESCRIPTION
**Pull request by westhomas**
...that are not unique to the user.

### CODE REVIEW

**Comment by pizzapanther** [comment]
I think i'm going to do this instead because otherwise the caching I was trying to achieve really doesn't work well: https://github.com/pizzapanther/GAE-Bulk-Mailer/pull/2/files

What do you think?

**Comment by westhomas** [comment]
I see what you're doing now. I didn't realize completely the effects of the caching.   This is much better.

**Comment by pizzapanther** [comment]
Let me know when you deploy this on CM, I'd like to send myself a test.

**Comment by westhomas** [comment]
It’s been done.  Version 2. 

We’ve sent about 48k already.

Wes Thomas
713-568-8288
www.edgecaselabs.com

On February 20, 2014 at 10:05:19 AM, Paul Bailey (notifications@github.com) wrote:

Let me know when you deploy this on CM, I'd like to send myself a test.

**Pull request merged**
